<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N1pH0RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n1pH0_r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'client' => ['privates', 'http_client.uri_template', 'getHttpClient_UriTemplateService', true],
        ], [
            'em' => '?',
            'client' => '?',
        ]);

        if (isset($container->privates['.service_locator.n1pH0_r'])) {
            return $container->privates['.service_locator.n1pH0_r'];
        }

        return $container->privates['.service_locator.n1pH0_r'] = $instance;
    }
}
