<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1rf5x2ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1rf5x2Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1rf5x2Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cour' => ['privates', '.errored..service_locator.1rf5x2Z.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.1rf5x2Z": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService', true],
        ], [
            'cour' => 'App\\Entity\\Cours',
            'chapitreRepository' => 'App\\Repository\\ChapitreRepository',
        ]);
    }
}
