<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2ZuYyIrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2ZuYyIr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'energie' => ['privates', '.errored..service_locator.2ZuYyIr.App\\Entity\\Energie', NULL, 'Cannot autowire service ".service_locator.2ZuYyIr": it needs an instance of "App\\Entity\\Energie" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'energie' => 'App\\Entity\\Energie',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.2ZuYyIr'])) {
            return $container->privates['.service_locator.2ZuYyIr'];
        }

        return $container->privates['.service_locator.2ZuYyIr'] = $instance;
    }
}
