<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VlY8At9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VlY8At9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VlY8At9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repas' => ['privates', '.errored..service_locator.VlY8At9.App\\Entity\\Repas', NULL, 'Cannot autowire service ".service_locator.VlY8At9": it needs an instance of "App\\Entity\\Repas" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repas' => 'App\\Entity\\Repas',
        ]);
    }
}
