<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NidAkdhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nidAkdh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nidAkdh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aliment' => ['privates', '.errored..service_locator.nidAkdh.App\\Entity\\Aliment', NULL, 'Cannot autowire service ".service_locator.nidAkdh": it needs an instance of "App\\Entity\\Aliment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'aliment' => 'App\\Entity\\Aliment',
        ]);
    }
}
