<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCStgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dC_Stge' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapitre' => ['privates', '.errored..service_locator.dC_Stge.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.dC_Stge": it needs an instance of "App\\Entity\\Chapitre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.dC_Stge'])) {
            return $container->privates['.service_locator.dC_Stge'];
        }

        return $container->privates['.service_locator.dC_Stge'] = $instance;
    }
}
