<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BDLr8J2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bDLr8J2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectif' => ['privates', '.errored..service_locator.bDLr8J2.App\\Entity\\Objectif', NULL, 'Cannot autowire service ".service_locator.bDLr8J2": it needs an instance of "App\\Entity\\Objectif" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'objectif' => 'App\\Entity\\Objectif',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.bDLr8J2'])) {
            return $container->privates['.service_locator.bDLr8J2'];
        }

        return $container->privates['.service_locator.bDLr8J2'] = $instance;
    }
}
