<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D2PhX5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d2_PhX5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aliment' => ['privates', '.errored..service_locator.d2_PhX5.App\\Entity\\Aliment', NULL, 'Cannot autowire service ".service_locator.d2_PhX5": it needs an instance of "App\\Entity\\Aliment" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'aliment' => 'App\\Entity\\Aliment',
            'em' => '?',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.d2_PhX5'])) {
            return $container->privates['.service_locator.d2_PhX5'];
        }

        return $container->privates['.service_locator.d2_PhX5'] = $instance;
    }
}
