<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dz4ImxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dz4_imx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dz4_imx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chapitreRepository' => ['privates', 'App\\Repository\\ChapitreRepository', 'getChapitreRepositoryService', true],
        ], [
            'chapitreRepository' => 'App\\Repository\\ChapitreRepository',
        ]);
    }
}
