<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitePhysiqueControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.32UMOBR.App\Controller\ActivitePhysiqueController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.32UMOBR'] ?? $container->load('get_ServiceLocator_32UMOBRService'));

        if (isset($container->privates['.service_locator.32UMOBR.App\\Controller\\ActivitePhysiqueController::edit()'])) {
            return $container->privates['.service_locator.32UMOBR.App\\Controller\\ActivitePhysiqueController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ActivitePhysiqueController::edit()', $container);

        if (isset($container->privates['.service_locator.32UMOBR.App\\Controller\\ActivitePhysiqueController::edit()'])) {
            return $container->privates['.service_locator.32UMOBR.App\\Controller\\ActivitePhysiqueController::edit()'];
        }

        return $container->privates['.service_locator.32UMOBR.App\\Controller\\ActivitePhysiqueController::edit()'] = $instance;
    }
}
