<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActiviteFrontControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FRx6L0h.App\Controller\Front\ActiviteFrontController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FRx6L0h.App\\Controller\\Front\\ActiviteFrontController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'activite' => ['privates', '.errored..service_locator.FRx6L0h.App\\Entity\\ActivitePhysique', NULL, 'Cannot autowire service ".service_locator.FRx6L0h": it needs an instance of "App\\Entity\\ActivitePhysique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'activite' => 'App\\Entity\\ActivitePhysique',
        ]))->withContext('App\\Controller\\Front\\ActiviteFrontController::show()', $container);
    }
}
