<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivitePhysiqueControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.asVeva..App\Controller\ActivitePhysiqueController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.asVeva..App\\Controller\\ActivitePhysiqueController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ActivitePhysiqueRepository', 'getActivitePhysiqueRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ActivitePhysiqueRepository',
        ]))->withContext('App\\Controller\\ActivitePhysiqueController::index()', $container);
    }
}
