<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentFrontControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d2_PhX5.App\Controller\Front\AlimentFrontController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.d2_PhX5'] ?? $container->load('get_ServiceLocator_D2PhX5Service'));

        if (isset($container->privates['.service_locator.d2_PhX5.App\\Controller\\Front\\AlimentFrontController::edit()'])) {
            return $container->privates['.service_locator.d2_PhX5.App\\Controller\\Front\\AlimentFrontController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\Front\\AlimentFrontController::edit()', $container);

        if (isset($container->privates['.service_locator.d2_PhX5.App\\Controller\\Front\\AlimentFrontController::edit()'])) {
            return $container->privates['.service_locator.d2_PhX5.App\\Controller\\Front\\AlimentFrontController::edit()'];
        }

        return $container->privates['.service_locator.d2_PhX5.App\\Controller\\Front\\AlimentFrontController::edit()'] = $instance;
    }
}
