<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentFrontControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ditgnzv.App\Controller\Front\AlimentFrontController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ditgnzv.App\\Controller\\Front\\AlimentFrontController::index()'] = ($container->privates['.service_locator.Ditgnzv'] ?? $container->load('get_ServiceLocator_DitgnzvService'))->withContext('App\\Controller\\Front\\AlimentFrontController::index()', $container);
    }
}
