<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zMNKn4P.App\Controller\AlimentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.zMNKn4P'] ?? $container->load('get_ServiceLocator_ZMNKn4PService'));

        if (isset($container->privates['.service_locator.zMNKn4P.App\\Controller\\AlimentController::delete()'])) {
            return $container->privates['.service_locator.zMNKn4P.App\\Controller\\AlimentController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\AlimentController::delete()', $container);

        if (isset($container->privates['.service_locator.zMNKn4P.App\\Controller\\AlimentController::delete()'])) {
            return $container->privates['.service_locator.zMNKn4P.App\\Controller\\AlimentController::delete()'];
        }

        return $container->privates['.service_locator.zMNKn4P.App\\Controller\\AlimentController::delete()'] = $instance;
    }
}
