<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlimentFrontControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nidAkdh.App\Controller\Front\AlimentFrontController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nidAkdh.App\\Controller\\Front\\AlimentFrontController::show()'] = ($container->privates['.service_locator.nidAkdh'] ?? $container->load('get_ServiceLocator_NidAkdhService'))->withContext('App\\Controller\\Front\\AlimentFrontController::show()', $container);
    }
}
