<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursFrontControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.INS41mO.App\Controller\Front\coursFrontController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.INS41mO'] ?? $container->load('get_ServiceLocator_INS41mOService'));

        if (isset($container->privates['.service_locator.INS41mO.App\\Controller\\Front\\coursFrontController::delete()'])) {
            return $container->privates['.service_locator.INS41mO.App\\Controller\\Front\\coursFrontController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Front\\coursFrontController::delete()', $container);

        if (isset($container->privates['.service_locator.INS41mO.App\\Controller\\Front\\coursFrontController::delete()'])) {
            return $container->privates['.service_locator.INS41mO.App\\Controller\\Front\\coursFrontController::delete()'];
        }

        return $container->privates['.service_locator.INS41mO.App\\Controller\\Front\\coursFrontController::delete()'] = $instance;
    }
}
