<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hSmOMdE.App\Controller\CoursController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.hSmOMdE'] ?? $container->load('get_ServiceLocator_HSmOMdEService'));

        if (isset($container->privates['.service_locator.hSmOMdE.App\\Controller\\CoursController::edit()'])) {
            return $container->privates['.service_locator.hSmOMdE.App\\Controller\\CoursController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\CoursController::edit()', $container);

        if (isset($container->privates['.service_locator.hSmOMdE.App\\Controller\\CoursController::edit()'])) {
            return $container->privates['.service_locator.hSmOMdE.App\\Controller\\CoursController::edit()'];
        }

        return $container->privates['.service_locator.hSmOMdE.App\\Controller\\CoursController::edit()'] = $instance;
    }
}
