<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SC4b9B3.App\Controller\CategorieController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.SC4b9B3.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.SC4b9B3": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\CategorieController::delete()', $container);

        if (isset($container->privates['.service_locator.SC4b9B3.App\\Controller\\CategorieController::delete()'])) {
            return $container->privates['.service_locator.SC4b9B3.App\\Controller\\CategorieController::delete()'];
        }

        return $container->privates['.service_locator.SC4b9B3.App\\Controller\\CategorieController::delete()'] = $instance;
    }
}
