<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursFrontControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wbxDpRj.App\Controller\Front\coursFrontController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wbxDpRj.App\\Controller\\Front\\coursFrontController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cours' => ['privates', '.errored..service_locator.wbxDpRj.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.wbxDpRj": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cours' => 'App\\Entity\\Cours',
        ]))->withContext('App\\Controller\\Front\\coursFrontController::show()', $container);
    }
}
