<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitreFrontControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dz4_imx.App\Controller\Front\chapitreFrontController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dz4_imx.App\\Controller\\Front\\chapitreFrontController::index()'] = ($container->privates['.service_locator.dz4_imx'] ?? $container->load('get_ServiceLocator_Dz4ImxService'))->withContext('App\\Controller\\Front\\chapitreFrontController::index()', $container);
    }
}
