<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitreControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dC_Stge.App\Controller\ChapitreController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.dC_Stge'] ?? $container->load('get_ServiceLocator_DCStgeService'));

        if (isset($container->privates['.service_locator.dC_Stge.App\\Controller\\ChapitreController::edit()'])) {
            return $container->privates['.service_locator.dC_Stge.App\\Controller\\ChapitreController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ChapitreController::edit()', $container);

        if (isset($container->privates['.service_locator.dC_Stge.App\\Controller\\ChapitreController::edit()'])) {
            return $container->privates['.service_locator.dC_Stge.App\\Controller\\ChapitreController::edit()'];
        }

        return $container->privates['.service_locator.dC_Stge.App\\Controller\\ChapitreController::edit()'] = $instance;
    }
}
