<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitreControllerbyCoursFrontService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1rf5x2Z.App\Controller\ChapitreController::byCoursFront()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1rf5x2Z.App\\Controller\\ChapitreController::byCoursFront()'] = ($container->privates['.service_locator.1rf5x2Z'] ?? $container->load('get_ServiceLocator_1rf5x2ZService'))->withContext('App\\Controller\\ChapitreController::byCoursFront()', $container);
    }
}
