<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitreControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z6FbZt8.App\Controller\ChapitreController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z6FbZt8.App\\Controller\\ChapitreController::show()'] = ($container->privates['.service_locator.Z6FbZt8'] ?? $container->load('get_ServiceLocator_Z6FbZt8Service'))->withContext('App\\Controller\\ChapitreController::show()', $container);
    }
}
