<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorie5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pFIajYl.App\Entity\Categorie' shared service.
     *
     * @return \App\Entity\Categorie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pFIajYl": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".');
    }
}
