<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepenseControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oWAo49H.App\Controller\DepenseController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oWAo49H.App\\Controller\\DepenseController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depense' => ['privates', '.errored..service_locator.oWAo49H.App\\Entity\\Depense', NULL, 'Cannot autowire service ".service_locator.oWAo49H": it needs an instance of "App\\Entity\\Depense" but this type has been excluded in "config/services.yaml".'],
        ], [
            'depense' => 'App\\Entity\\Depense',
        ]))->withContext('App\\Controller\\DepenseController::show()', $container);
    }
}
