<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepenseControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xRJd3ag.App\Controller\DepenseController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xRJd3ag.App\\Controller\\DepenseController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depenseRepository' => ['privates', 'App\\Repository\\DepenseRepository', 'getDepenseRepositoryService', true],
        ], [
            'depenseRepository' => 'App\\Repository\\DepenseRepository',
        ]))->withContext('App\\Controller\\DepenseController::index()', $container);
    }
}
