<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepenseControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f6Xg.Vn.App\Controller\DepenseController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.f6Xg.Vn'] ?? $container->load('get_ServiceLocator_F6Xg_VnService'));

        if (isset($container->privates['.service_locator.f6Xg.Vn.App\\Controller\\DepenseController::new()'])) {
            return $container->privates['.service_locator.f6Xg.Vn.App\\Controller\\DepenseController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\DepenseController::new()', $container);

        if (isset($container->privates['.service_locator.f6Xg.Vn.App\\Controller\\DepenseController::new()'])) {
            return $container->privates['.service_locator.f6Xg.Vn.App\\Controller\\DepenseController::new()'];
        }

        return $container->privates['.service_locator.f6Xg.Vn.App\\Controller\\DepenseController::new()'] = $instance;
    }
}
