<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergie2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y51WqkK.App\Entity\Energie' shared service.
     *
     * @return \App\Entity\Energie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Y51WqkK": it needs an instance of "App\\Entity\\Energie" but this type has been excluded in "config/services.yaml".');
    }
}
