<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergieControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y51WqkK.App\Controller\Front\EnergieController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'energie' => ['privates', '.errored..service_locator.Y51WqkK.App\\Entity\\Energie', NULL, 'Cannot autowire service ".service_locator.Y51WqkK": it needs an instance of "App\\Entity\\Energie" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'gemini' => ['privates', 'App\\Service\\GeminiRecommandationService', 'getGeminiRecommandationServiceService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'energie' => 'App\\Entity\\Energie',
            'em' => '?',
            'gemini' => 'App\\Service\\GeminiRecommandationService',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\Front\\EnergieController::update()', $container);

        if (isset($container->privates['.service_locator.Y51WqkK.App\\Controller\\Front\\EnergieController::update()'])) {
            return $container->privates['.service_locator.Y51WqkK.App\\Controller\\Front\\EnergieController::update()'];
        }

        return $container->privates['.service_locator.Y51WqkK.App\\Controller\\Front\\EnergieController::update()'] = $instance;
    }
}
