<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergieControlleraddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jao9fFu.App\Controller\Front\EnergieController::add()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\EnergieRepository', 'getEnergieRepositoryService', true],
            'gemini' => ['privates', 'App\\Service\\GeminiRecommandationService', 'getGeminiRecommandationServiceService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\EnergieRepository',
            'gemini' => 'App\\Service\\GeminiRecommandationService',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\Front\\EnergieController::add()', $container);

        if (isset($container->privates['.service_locator.jao9fFu.App\\Controller\\Front\\EnergieController::add()'])) {
            return $container->privates['.service_locator.jao9fFu.App\\Controller\\Front\\EnergieController::add()'];
        }

        return $container->privates['.service_locator.jao9fFu.App\\Controller\\Front\\EnergieController::add()'] = $instance;
    }
}
