<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergieControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xiBYd8E.App\Controller\Front\EnergieController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xiBYd8E.App\\Controller\\Front\\EnergieController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\EnergieRepository', 'getEnergieRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\EnergieRepository',
        ]))->withContext('App\\Controller\\Front\\EnergieController::index()', $container);
    }
}
