<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontDepenseControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uUClb_Q.App\Controller\Front\FrontDepenseController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uUClb_Q.App\\Controller\\Front\\FrontDepenseController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depenseRepository' => ['privates', 'App\\Repository\\DepenseRepository', 'getDepenseRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'depenseRepository' => 'App\\Repository\\DepenseRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Front\\FrontDepenseController::index()', $container);
    }
}
