<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontDepenseControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B2jkzKw.App\Controller\Front\FrontDepenseController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depense' => ['privates', '.errored..service_locator.B2jkzKw.App\\Entity\\Depense', NULL, 'Cannot autowire service ".service_locator.B2jkzKw": it needs an instance of "App\\Entity\\Depense" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'depense' => 'App\\Entity\\Depense',
            'entityManager' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Front\\FrontDepenseController::delete()', $container);

        if (isset($container->privates['.service_locator.B2jkzKw.App\\Controller\\Front\\FrontDepenseController::delete()'])) {
            return $container->privates['.service_locator.B2jkzKw.App\\Controller\\Front\\FrontDepenseController::delete()'];
        }

        return $container->privates['.service_locator.B2jkzKw.App\\Controller\\Front\\FrontDepenseController::delete()'] = $instance;
    }
}
