<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontDepenseControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._IAS4Sx.App\Controller\Front\FrontDepenseController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._IAS4Sx.App\\Controller\\Front\\FrontDepenseController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depense' => ['privates', '.errored..service_locator._IAS4Sx.App\\Entity\\Depense', NULL, 'Cannot autowire service ".service_locator._IAS4Sx": it needs an instance of "App\\Entity\\Depense" but this type has been excluded in "config/services.yaml".'],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'depense' => 'App\\Entity\\Depense',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Front\\FrontDepenseController::show()', $container);
    }
}
