<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontRepasControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HzTnCBJ.App\Controller\Front\FrontRepasController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repas' => ['privates', '.errored..service_locator.HzTnCBJ.App\\Entity\\Repas', NULL, 'Cannot autowire service ".service_locator.HzTnCBJ": it needs an instance of "App\\Entity\\Repas" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'repas' => 'App\\Entity\\Repas',
            'em' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\Front\\FrontRepasController::edit()', $container);

        if (isset($container->privates['.service_locator.HzTnCBJ.App\\Controller\\Front\\FrontRepasController::edit()'])) {
            return $container->privates['.service_locator.HzTnCBJ.App\\Controller\\Front\\FrontRepasController::edit()'];
        }

        return $container->privates['.service_locator.HzTnCBJ.App\\Controller\\Front\\FrontRepasController::edit()'] = $instance;
    }
}
