<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontCategorieControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mzerhgx.App\Controller\Front\FrontCategorieController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.mzerhgx'] ?? $container->load('get_ServiceLocator_MzerhgxService'));

        if (isset($container->privates['.service_locator.mzerhgx.App\\Controller\\Front\\FrontCategorieController::new()'])) {
            return $container->privates['.service_locator.mzerhgx.App\\Controller\\Front\\FrontCategorieController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\Front\\FrontCategorieController::new()', $container);

        if (isset($container->privates['.service_locator.mzerhgx.App\\Controller\\Front\\FrontCategorieController::new()'])) {
            return $container->privates['.service_locator.mzerhgx.App\\Controller\\Front\\FrontCategorieController::new()'];
        }

        return $container->privates['.service_locator.mzerhgx.App\\Controller\\Front\\FrontCategorieController::new()'] = $instance;
    }
}
