<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontRepasControllerfromProposalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0N19eS..App\Controller\Front\FrontRepasController::fromProposal()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'alimentRepo' => ['privates', 'App\\Repository\\AlimentRepository', 'getAlimentRepositoryService', true],
        ], [
            'em' => '?',
            'alimentRepo' => 'App\\Repository\\AlimentRepository',
        ]))->withContext('App\\Controller\\Front\\FrontRepasController::fromProposal()', $container);

        if (isset($container->privates['.service_locator.0N19eS..App\\Controller\\Front\\FrontRepasController::fromProposal()'])) {
            return $container->privates['.service_locator.0N19eS..App\\Controller\\Front\\FrontRepasController::fromProposal()'];
        }

        return $container->privates['.service_locator.0N19eS..App\\Controller\\Front\\FrontRepasController::fromProposal()'] = $instance;
    }
}
