<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontCategorieControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pFIajYl.App\Controller\Front\FrontCategorieController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pFIajYl.App\\Controller\\Front\\FrontCategorieController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.pFIajYl.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.pFIajYl": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\Front\\FrontCategorieController::show()', $container);
    }
}
