<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiRecommandationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GeminiRecommandationService' shared autowired service.
     *
     * @return \App\Service\GeminiRecommandationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GeminiRecommandationService.php';

        return $container->privates['App\\Service\\GeminiRecommandationService'] = new \App\Service\GeminiRecommandationService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GEMINI_API_KEY'));
    }
}
