<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bDLr8J2.App\Controller\ObjectifController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.bDLr8J2'] ?? $container->load('get_ServiceLocator_BDLr8J2Service'));

        if (isset($container->privates['.service_locator.bDLr8J2.App\\Controller\\ObjectifController::edit()'])) {
            return $container->privates['.service_locator.bDLr8J2.App\\Controller\\ObjectifController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ObjectifController::edit()', $container);

        if (isset($container->privates['.service_locator.bDLr8J2.App\\Controller\\ObjectifController::edit()'])) {
            return $container->privates['.service_locator.bDLr8J2.App\\Controller\\ObjectifController::edit()'];
        }

        return $container->privates['.service_locator.bDLr8J2.App\\Controller\\ObjectifController::edit()'] = $instance;
    }
}
