<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifFrontControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hN49sHz.App\Controller\Front\ObjectifFrontController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hN49sHz.App\\Controller\\Front\\ObjectifFrontController::show()'] = ($container->privates['.service_locator.hN49sHz'] ?? $container->load('get_ServiceLocator_HN49sHzService'))->withContext('App\\Controller\\Front\\ObjectifFrontController::show()', $container);
    }
}
