<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifFrontControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n1pH0_r.App\Controller\Front\ObjectifFrontController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.n1pH0_r'] ?? $container->load('get_ServiceLocator_N1pH0RService'));

        if (isset($container->privates['.service_locator.n1pH0_r.App\\Controller\\Front\\ObjectifFrontController::index()'])) {
            return $container->privates['.service_locator.n1pH0_r.App\\Controller\\Front\\ObjectifFrontController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\Front\\ObjectifFrontController::index()', $container);

        if (isset($container->privates['.service_locator.n1pH0_r.App\\Controller\\Front\\ObjectifFrontController::index()'])) {
            return $container->privates['.service_locator.n1pH0_r.App\\Controller\\Front\\ObjectifFrontController::index()'];
        }

        return $container->privates['.service_locator.n1pH0_r.App\\Controller\\Front\\ObjectifFrontController::index()'] = $instance;
    }
}
