<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VlY8At9.App\Controller\RepasController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VlY8At9.App\\Controller\\RepasController::show()'] = ($container->privates['.service_locator.VlY8At9'] ?? $container->load('get_ServiceLocator_VlY8At9Service'))->withContext('App\\Controller\\RepasController::show()', $container);
    }
}
