<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommandationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0BWxEHZ.App\Controller\Front\RecommandationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0BWxEHZ'] ?? $container->load('get_ServiceLocator_0BWxEHZService'));

        if (isset($container->privates['.service_locator.0BWxEHZ.App\\Controller\\Front\\RecommandationController::delete()'])) {
            return $container->privates['.service_locator.0BWxEHZ.App\\Controller\\Front\\RecommandationController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\Front\\RecommandationController::delete()', $container);

        if (isset($container->privates['.service_locator.0BWxEHZ.App\\Controller\\Front\\RecommandationController::delete()'])) {
            return $container->privates['.service_locator.0BWxEHZ.App\\Controller\\Front\\RecommandationController::delete()'];
        }

        return $container->privates['.service_locator.0BWxEHZ.App\\Controller\\Front\\RecommandationController::delete()'] = $instance;
    }
}
