<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasControllerexportPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nJ5Fw6q.App\Controller\RepasController::exportPdf()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repas' => ['privates', '.errored..service_locator.nJ5Fw6q.App\\Entity\\Repas', NULL, 'Cannot autowire service ".service_locator.nJ5Fw6q": it needs an instance of "App\\Entity\\Repas" but this type has been excluded in "config/services.yaml".'],
            'pdfService' => ['privates', 'App\\Service\\RepasPdfService', 'getRepasPdfServiceService', true],
        ], [
            'repas' => 'App\\Entity\\Repas',
            'pdfService' => 'App\\Service\\RepasPdfService',
        ]))->withContext('App\\Controller\\RepasController::exportPdf()', $container);

        if (isset($container->privates['.service_locator.nJ5Fw6q.App\\Controller\\RepasController::exportPdf()'])) {
            return $container->privates['.service_locator.nJ5Fw6q.App\\Controller\\RepasController::exportPdf()'];
        }

        return $container->privates['.service_locator.nJ5Fw6q.App\\Controller\\RepasController::exportPdf()'] = $instance;
    }
}
