<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasPdfServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RepasPdfService' shared autowired service.
     *
     * @return \App\Service\RepasPdfService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RepasPdfService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Service\\RepasPdfService'])) {
            return $container->privates['App\\Service\\RepasPdfService'];
        }

        $instance = new \App\Service\RepasPdfService($a, ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));

        if (isset($container->privates['App\\Service\\RepasPdfService'])) {
            return $container->privates['App\\Service\\RepasPdfService'];
        }

        return $container->privates['App\\Service\\RepasPdfService'] = $instance;
    }
}
