<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepasControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QkVGd0t.App\Controller\RepasController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.QkVGd0t'] ?? $container->load('get_ServiceLocator_QkVGd0tService'));

        if (isset($container->privates['.service_locator.QkVGd0t.App\\Controller\\RepasController::edit()'])) {
            return $container->privates['.service_locator.QkVGd0t.App\\Controller\\RepasController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\RepasController::edit()', $container);

        if (isset($container->privates['.service_locator.QkVGd0t.App\\Controller\\RepasController::edit()'])) {
            return $container->privates['.service_locator.QkVGd0t.App\\Controller\\RepasController::edit()'];
        }

        return $container->privates['.service_locator.QkVGd0t.App\\Controller\\RepasController::edit()'] = $instance;
    }
}
