<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordRequestCrudControllercreateIndexQueryBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Gfu5xe.App\Controller\Admin\ResetPasswordRequestCrudController::createIndexQueryBuilder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Gfu5xe.App\\Controller\\Admin\\ResetPasswordRequestCrudController::createIndexQueryBuilder()'] = ($container->privates['.service_locator._Gfu5xe'] ?? $container->load('get_ServiceLocator_Gfu5xeService'))->withContext('App\\Controller\\Admin\\ResetPasswordRequestCrudController::createIndexQueryBuilder()', $container);
    }
}
