<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommandationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0BWxEHZ.App\Entity\Recommandation' shared service.
     *
     * @return \App\Entity\Recommandation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0BWxEHZ": it needs an instance of "App\\Entity\\Recommandation" but this type has been excluded in "config/services.yaml".');
    }
}
