<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerblockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8m8R3s_.App\Controller\UserController::block()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.8m8R3s_'] ?? $container->load('get_ServiceLocator_8m8R3sService'));

        if (isset($container->privates['.service_locator.8m8R3s_.App\\Controller\\UserController::block()'])) {
            return $container->privates['.service_locator.8m8R3s_.App\\Controller\\UserController::block()'];
        }

        $instance = $a->withContext('App\\Controller\\UserController::block()', $container);

        if (isset($container->privates['.service_locator.8m8R3s_.App\\Controller\\UserController::block()'])) {
            return $container->privates['.service_locator.8m8R3s_.App\\Controller\\UserController::block()'];
        }

        return $container->privates['.service_locator.8m8R3s_.App\\Controller\\UserController::block()'] = $instance;
    }
}
