<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4VCqJOp.App\Controller\UserController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UserController::new()', $container);

        if (isset($container->privates['.service_locator.4VCqJOp.App\\Controller\\UserController::new()'])) {
            return $container->privates['.service_locator.4VCqJOp.App\\Controller\\UserController::new()'];
        }

        return $container->privates['.service_locator.4VCqJOp.App\\Controller\\UserController::new()'] = $instance;
    }
}
