<?php

namespace Container9fLThb7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WhE_99h.App\Controller\UserController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.WhE_99h.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.WhE_99h": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UserController::edit()', $container);

        if (isset($container->privates['.service_locator.WhE_99h.App\\Controller\\UserController::edit()'])) {
            return $container->privates['.service_locator.WhE_99h.App\\Controller\\UserController::edit()'];
        }

        return $container->privates['.service_locator.WhE_99h.App\\Controller\\UserController::edit()'] = $instance;
    }
}
