parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\GeminiRecommandationService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\GroqService:
        arguments:
            $groqApiKey: '%env(GROQ_API_KEY)%'

    App\Service\MailingService:
        arguments:
            $mailerFrom:     '%env(MAILER_FROM)%'
            $mailerFromName: '%env(MAILER_FROM_NAME)%'
            $emailDemo:      '%env(bool:EMAIL_DEMO)%'
