parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Services généraux
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Kernel.php'

    # Contrôleurs
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
