parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\GeminiRecommandationService:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
